name : cronsito

adon : 
      schedule:
               - cron : "*/5 * * * *"
jobs:
    run-script:
              runs-on: ubuntu-latest
              env:
                  TELEGRAM: 6859517839:AAF9Ofn_q6ia9XLaoP0BiAIfe68L5ZkN0Us

              steps:
                    - name: siu
                      uses: actions/checkout@v2
                    
                    - name: instalando dependencias
                      run : |
                            pip install -r requirements.txt
                     
                    - name : corriendo script  
                      run: python cron.py 

